## Compare pretrained backbones

In [ ]:
from sklearn.model_selection import StratifiedGroupKFold, StratifiedKFold
from configs.cfg import CFG
from dataset.biomass_dataset import *
from utils.augs import *
from configs.deterministic import *
from models.models import *
from train.train import *
from dataset.preprocess_data import *

if __name__ == "__main__":
    set_seed(CFG.SEED,CFG.DETERMINISTIC)
    df_wide = get_df()
    
    fold_indices = {}

    # sgkf = StratifiedGroupKFold(n_splits=CFG.N_FOLDS, shuffle=True, random_state=CFG.SEED)
    # splitter = sgkf.split(X=df_wide, y=df_wide['biomass_bin'], groups=df_wide['group'])
    skf = StratifiedKFold(n_splits=CFG.N_FOLDS, shuffle=True, random_state=204)
    splitter = skf.split(X=df_wide, y=df_wide['biomass_bin'])

    for fold_id, (train_idx, val_idx) in enumerate(splitter):
        fold_indices[fold_id] = val_idx
        print(f"Fold {fold_id} captured: {len(val_idx)} images")

    # A. Define which folds go where
    train_folds = [1, 2, 3, 4]
    val_fold    = 0
    test_fold   = 4

    # B. Construct the final index lists
    # np.concatenate joins the arrays of indices together
    train_idx_final = np.concatenate([fold_indices[f] for f in train_folds])
    val_idx_final   = fold_indices[val_fold]
    test_idx_final  = fold_indices[test_fold]
    # C. Create the DataFrames
    train_df = df_wide.iloc[train_idx_final].reset_index(drop=True)
    val_df   = df_wide.iloc[val_idx_final].reset_index(drop=True)
    # test_df  = df_wide.iloc[test_idx_final].reset_index(drop=True)
    # print(df_wide.head())
    print(f"Train Size: {len(train_df)}") # Should be roughly 60%
    print(f"Val Size:   {len(val_df)}")   # Should be roughly 20%
    # print(f"Test Size:  {len(test_df)}")  # Should be roughly 20%
    train_labels_tensor = torch.tensor(
        train_df[["Dry_Green_g", "Dry_Dead_g", "Dry_Clover_g", "GDM_g", "Dry_Total_g"]].values, 
        dtype=torch.float32
    )
    # print(calculate_deltas(train_labels_tensor))
    group_name = f"Date_{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    best_r2 = train_base(train_df,val_df, 0,group_name=group_name)
# Epoch 100 | TrainLoss 71.63072 | ValLoss 1655.10278 | ValR² -0.1487 (BEST)

/home/teo/repos/CSIRO---Image2Biomass-Prediction/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Loading data...
357 training images
Fold 0 captured: 72 images
Fold 1 captured: 72 images
Fold 2 captured: 71 images
Fold 3 captured: 71 images
Fold 4 captured: 71 images
Train Size: 285
Val Size:   72
Target       | MAD      | Proposed Delta | Strategy
-------------------------------------------------------
Dry_Green_g  | 12.63     | 37.46           | Balanced
Dry_Dead_g   | 5.94     | 17.61           | Balanced
Dry_Clover_g | 1.50     | 2.22           | Robust
GDM_g        | 12.56     | 55.88           | MSE-ish
Dry_Total_g  | 16.27     | 72.36           | MSE-ish
Building model...
vit_small_patch16_dinov3 parameters: 21586944


Pretrained weights loaded (CPU)
Freezing backbone parameters.


train:   0%|          | 0/36 [00:00<?, ?it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:   6%|▌         | 2/36 [00:01<00:21,  1.55it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  11%|█         | 4/36 [00:01<00:10,  2.94it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  17%|█▋        | 6/36 [00:02<00:07,  3.95it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  22%|██▏       | 8/36 [00:02<00:06,  4.57it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  28%|██▊       | 10/36 [00:03<00:05,  4.90it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  33%|███▎      | 12/36 [00:03<00:04,  5.08it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  39%|███▉      | 14/36 [00:03<00:04,  5.18it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  44%|████▍     | 16/36 [00:04<00:03,  5.21it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  50%|█████     | 18/36 [00:04<00:03,  5.21it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  56%|█████▌    | 20/36 [00:04<00:03,  5.24it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  61%|██████    | 22/36 [00:05<00:02,  5.26it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  67%|██████▋   | 24/36 [00:05<00:02,  5.27it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  72%|███████▏  | 26/36 [00:06<00:01,  5.26it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  78%|███████▊  | 28/36 [00:06<00:01,  5.25it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  83%|████████▎ | 30/36 [00:06<00:01,  5.26it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  89%|████████▉ | 32/36 [00:07<00:00,  5.27it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


train:  94%|█████████▍| 34/36 [00:07<00:00,  5.27it/s]

tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')
tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


tensor([0.9850, 0.9850, 0.9850, 0.9867, 0.9917], device='cuda:0')


Epoch 01 | TrainLoss 5990.29474 | ValLoss 2081.63722 | ValR² -1.2448 (BEST) | GreenR² -0.83025 | DeadR² -1.02757 | CloverR² -0.21056 | GDMR² -1.43524 | TotalR² -2.31735
SAVED (R²: -1.2448)


train:   3%|▎         | 1/36 [00:00<00:25,  1.36it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.19it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.17it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.69it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.96it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:04,  5.06it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.13it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.13it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.19it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.22it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.20it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:04<00:02,  5.22it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.23it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.23it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.23it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.24it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:06<00:00,  5.25it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.25it/s]

tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')
tensor([0.9700, 0.9700, 0.9700, 0.9733, 0.9833], device='cuda:0')


Epoch 02 | TrainLoss 5386.11430 | ValLoss 1505.08086 | ValR² -0.6230 (BEST) | GreenR² -0.39253 | DeadR² -0.19186 | CloverR² -0.10397 | GDMR² -1.01924 | TotalR² -1.29361
SAVED (R²: -0.6230)


train:   3%|▎         | 1/36 [00:00<00:25,  1.35it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.15it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.12it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.67it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.94it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:04,  5.08it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.15it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.18it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.19it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.19it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.20it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:04<00:02,  5.21it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.21it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.22it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.22it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.23it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:06<00:00,  5.23it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.23it/s]

tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')
tensor([0.9550, 0.9550, 0.9550, 0.9600, 0.9750], device='cuda:0')


Epoch 03 | TrainLoss 2457.54255 | ValLoss 719.22269 | ValR² 0.2244 (BEST) | GreenR² 0.06963 | DeadR² 0.08621 | CloverR² 0.14032 | GDMR² 0.01772 | TotalR² -0.01479
SAVED (R²: 0.2244)


train:   3%|▎         | 1/36 [00:00<00:24,  1.43it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.26it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.20it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.70it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.95it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:04,  5.07it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.14it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.17it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.18it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.20it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.21it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:04<00:02,  5.20it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.21it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.20it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.20it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.21it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:06<00:00,  5.21it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.21it/s]

tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')
tensor([0.9400, 0.9400, 0.9400, 0.9467, 0.9667], device='cuda:0')


/home/teo/repos/CSIRO---Image2Biomass-Prediction/.venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:243: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)


Epoch 04 | TrainLoss 1676.91903 | ValLoss 577.40740 | ValR² 0.3773 (BEST) | GreenR² 0.26221 | DeadR² 0.06919 | CloverR² 0.48577 | GDMR² 0.22355 | TotalR² 0.17843
SAVED (R²: 0.3773)


train:   3%|▎         | 1/36 [00:00<00:26,  1.33it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:   6%|▌         | 2/36 [00:00<00:14,  2.33it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  11%|█         | 4/36 [00:01<00:08,  3.70it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  17%|█▋        | 6/36 [00:01<00:06,  4.37it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  22%|██▏       | 8/36 [00:02<00:05,  4.78it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  28%|██▊       | 10/36 [00:02<00:05,  4.99it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  33%|███▎      | 12/36 [00:02<00:04,  5.10it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  39%|███▉      | 14/36 [00:03<00:04,  5.14it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  44%|████▍     | 16/36 [00:03<00:03,  5.18it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  50%|█████     | 18/36 [00:04<00:03,  5.18it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  56%|█████▌    | 20/36 [00:04<00:03,  5.19it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  61%|██████    | 22/36 [00:04<00:02,  5.19it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  67%|██████▋   | 24/36 [00:05<00:02,  5.18it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  72%|███████▏  | 26/36 [00:05<00:01,  5.18it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  78%|███████▊  | 28/36 [00:05<00:01,  5.19it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  83%|████████▎ | 30/36 [00:06<00:01,  5.18it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  89%|████████▉ | 32/36 [00:06<00:00,  5.19it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


train:  94%|█████████▍| 34/36 [00:07<00:00,  5.20it/s]

tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')
tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


tensor([0.9250, 0.9250, 0.9250, 0.9333, 0.9583], device='cuda:0')


Epoch 05 | TrainLoss 1124.30286 | ValLoss 426.66979 | ValR² 0.5399 (BEST) | GreenR² 0.43708 | DeadR² 0.16423 | CloverR² 0.66979 | GDMR² 0.37465 | TotalR² 0.41713
SAVED (R²: 0.5399)


train:   3%|▎         | 1/36 [00:00<00:24,  1.42it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.22it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.15it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.60it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.90it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:04,  5.04it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.10it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.14it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.17it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.17it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.17it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:04<00:02,  5.17it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.18it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.18it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.18it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.19it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:06<00:00,  5.19it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.18it/s]

tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')
tensor([0.9100, 0.9100, 0.9100, 0.9200, 0.9500], device='cuda:0')


Epoch 06 | TrainLoss 861.49605 | ValLoss 364.12044 | ValR² 0.6073 (BEST) | GreenR² 0.54420 | DeadR² 0.07438 | CloverR² 0.60812 | GDMR² 0.47031 | TotalR² 0.50730
SAVED (R²: 0.6073)


train:   3%|▎         | 1/36 [00:00<00:27,  1.26it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.04it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.06it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.60it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.89it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:04,  5.03it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.09it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.12it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.15it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.15it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.16it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.18it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.17it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.18it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.18it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.19it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:06<00:00,  5.19it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.19it/s]

tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')
tensor([0.8950, 0.8950, 0.8950, 0.9067, 0.9417], device='cuda:0')


Epoch 07 | TrainLoss 813.84346 | ValLoss 351.38297 | ValR² 0.6211 (BEST) | GreenR² 0.57898 | DeadR² 0.23088 | CloverR² 0.65452 | GDMR² 0.48326 | TotalR² 0.51772
SAVED (R²: 0.6211)


train:   3%|▎         | 1/36 [00:00<00:23,  1.50it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:09,  3.31it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.14it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.65it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.90it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:04,  5.03it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.09it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.14it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.14it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.15it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.15it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:04<00:02,  5.16it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.17it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.16it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.16it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.17it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:06<00:00,  5.18it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.18it/s]

tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')
tensor([0.8800, 0.8800, 0.8800, 0.8933, 0.9333], device='cuda:0')


Epoch 08 | TrainLoss 675.66192 | ValLoss 341.85565 | ValR² 0.6314 (BEST) | GreenR² 0.59093 | DeadR² 0.16812 | CloverR² 0.73011 | GDMR² 0.50568 | TotalR² 0.52771
SAVED (R²: 0.6314)


train:   3%|▎         | 1/36 [00:00<00:25,  1.36it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.17it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.12it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.64it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.90it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:04,  5.04it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.10it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.12it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.12it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.14it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.15it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.14it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.15it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.14it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.15it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.16it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:06<00:00,  5.17it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.17it/s]

tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')
tensor([0.8650, 0.8650, 0.8650, 0.8800, 0.9250], device='cuda:0')


train:   3%|▎         | 1/36 [00:00<00:24,  1.41it/s] 

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.22it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.16it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.64it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.90it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:04,  5.02it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.08it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.11it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.12it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.11it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.13it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.14it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.14it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.15it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.16it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.16it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:06<00:00,  5.16it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.16it/s]

tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')
tensor([0.8500, 0.8500, 0.8500, 0.8667, 0.9167], device='cuda:0')


Epoch 10 | TrainLoss 599.81866 | ValLoss 339.04582 | ValR² 0.6344 (BEST) | GreenR² 0.57171 | DeadR² 0.18960 | CloverR² 0.76572 | GDMR² 0.49754 | TotalR² 0.53851
SAVED (R²: 0.6344)


train:   3%|▎         | 1/36 [00:00<00:26,  1.32it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.10it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  3.99it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  17%|█▋        | 6/36 [00:01<00:06,  4.31it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  22%|██▏       | 8/36 [00:02<00:05,  4.69it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  28%|██▊       | 10/36 [00:02<00:05,  4.90it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  33%|███▎      | 12/36 [00:02<00:04,  5.03it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  39%|███▉      | 14/36 [00:03<00:04,  5.08it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  44%|████▍     | 16/36 [00:03<00:03,  5.11it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  50%|█████     | 18/36 [00:04<00:03,  5.13it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  56%|█████▌    | 20/36 [00:04<00:03,  5.14it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  61%|██████    | 22/36 [00:04<00:02,  5.14it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  67%|██████▋   | 24/36 [00:05<00:02,  5.14it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  72%|███████▏  | 26/36 [00:05<00:01,  5.13it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  78%|███████▊  | 28/36 [00:06<00:01,  5.13it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  83%|████████▎ | 30/36 [00:06<00:01,  5.13it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  89%|████████▉ | 32/36 [00:06<00:00,  5.15it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


train:  94%|█████████▍| 34/36 [00:07<00:00,  5.16it/s]

tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')
tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


tensor([0.8350, 0.8350, 0.8350, 0.8533, 0.9083], device='cuda:0')


Epoch 11 | TrainLoss 566.87094 | ValLoss 323.39777 | ValR² 0.6513 (BEST) | GreenR² 0.62345 | DeadR² 0.17870 | CloverR² 0.79208 | GDMR² 0.52444 | TotalR² 0.55318
SAVED (R²: 0.6513)


train:   3%|▎         | 1/36 [00:00<00:26,  1.33it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.10it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.06it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.56it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  22%|██▏       | 8/36 [00:02<00:06,  4.53it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.71it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:05,  4.92it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.02it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.07it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.10it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.10it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.08it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.10it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.13it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.14it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.15it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.16it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:07<00:00,  5.17it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.17it/s]

tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')
tensor([0.8200, 0.8200, 0.8200, 0.8400, 0.9000], device='cuda:0')


Epoch 12 | TrainLoss 540.90006 | ValLoss 319.53853 | ValR² 0.6554 (BEST) | GreenR² 0.62705 | DeadR² -0.02105 | CloverR² 0.81292 | GDMR² 0.50934 | TotalR² 0.57175
SAVED (R²: 0.6554)


train:   3%|▎         | 1/36 [00:00<00:25,  1.36it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.17it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.09it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.61it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.89it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:04,  5.02it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.07it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.10it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.12it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.12it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.14it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.15it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.15it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.15it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.15it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.16it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:06<00:00,  5.17it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.17it/s]

tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')
tensor([0.8050, 0.8050, 0.8050, 0.8267, 0.8917], device='cuda:0')


Epoch 13 | TrainLoss 516.17970 | ValLoss 311.75077 | ValR² 0.6638 (BEST) | GreenR² 0.66373 | DeadR² 0.18055 | CloverR² 0.80736 | GDMR² 0.55105 | TotalR² 0.56129
SAVED (R²: 0.6638)


train:   3%|▎         | 1/36 [00:00<00:26,  1.33it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.10it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.06it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.57it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.83it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:05,  4.99it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.04it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.07it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.09it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.11it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.10it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.11it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.12it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.13it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.13it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.14it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:07<00:00,  5.14it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.14it/s]

tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')
tensor([0.7900, 0.7900, 0.7900, 0.8133, 0.8833], device='cuda:0')


train:   3%|▎         | 1/36 [00:00<00:27,  1.26it/s] 

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:   6%|▌         | 2/36 [00:00<00:15,  2.26it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  11%|█         | 4/36 [00:01<00:08,  3.60it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  17%|█▋        | 6/36 [00:01<00:06,  4.33it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  22%|██▏       | 8/36 [00:02<00:05,  4.70it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  28%|██▊       | 10/36 [00:02<00:05,  4.88it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  33%|███▎      | 12/36 [00:02<00:04,  5.00it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  39%|███▉      | 14/36 [00:03<00:04,  5.04it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  44%|████▍     | 16/36 [00:03<00:03,  5.06it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  50%|█████     | 18/36 [00:04<00:03,  5.10it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  56%|█████▌    | 20/36 [00:04<00:03,  5.11it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  61%|██████    | 22/36 [00:04<00:02,  5.12it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  67%|██████▋   | 24/36 [00:05<00:02,  5.13it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  72%|███████▏  | 26/36 [00:05<00:01,  5.13it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  78%|███████▊  | 28/36 [00:06<00:01,  5.12it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  83%|████████▎ | 30/36 [00:06<00:01,  5.12it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  89%|████████▉ | 32/36 [00:06<00:00,  5.13it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:  94%|█████████▍| 34/36 [00:07<00:00,  5.14it/s]

tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')
tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


tensor([0.7750, 0.7750, 0.7750, 0.8000, 0.8750], device='cuda:0')


train:   3%|▎         | 1/36 [00:00<00:26,  1.30it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.08it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.07it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.60it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.87it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:04,  5.00it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.06it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.10it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.11it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.11it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.11it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.13it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.12it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.12it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.13it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.14it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:07<00:00,  5.14it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.14it/s]

tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')
tensor([0.7600, 0.7600, 0.7600, 0.7867, 0.8667], device='cuda:0')


Epoch 16 | TrainLoss 465.45604 | ValLoss 298.87236 | ValR² 0.6777 (BEST) | GreenR² 0.67974 | DeadR² 0.23884 | CloverR² 0.83253 | GDMR² 0.55745 | TotalR² 0.58185
SAVED (R²: 0.6777)


train:   3%|▎         | 1/36 [00:00<00:26,  1.34it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.12it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.08it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.62it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.88it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:05,  4.98it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.05it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.09it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.09it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.10it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.11it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.10it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.11it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.11it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.12it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.13it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:07<00:00,  5.14it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.14it/s]

tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')
tensor([0.7450, 0.7450, 0.7450, 0.7733, 0.8583], device='cuda:0')


train:   3%|▎         | 1/36 [00:00<00:26,  1.34it/s] 

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.13it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.10it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.61it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.87it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:05,  4.99it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.06it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.07it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.02it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.06it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.08it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.08it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.05it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.08it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.10it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.12it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:07<00:00,  5.12it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.13it/s]

tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')
tensor([0.7300, 0.7300, 0.7300, 0.7600, 0.8500], device='cuda:0')


train:   3%|▎         | 1/36 [00:00<00:26,  1.32it/s] 

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.10it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.07it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.58it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.85it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:05,  4.99it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.05it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.08it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.10it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.11it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.11it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.11it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.11it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.11it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.12it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.12it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:07<00:00,  5.13it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.13it/s]

tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')
tensor([0.7150, 0.7150, 0.7150, 0.7467, 0.8417], device='cuda:0')


Epoch 19 | TrainLoss 395.16941 | ValLoss 292.10345 | ValR² 0.6850 (BEST) | GreenR² 0.66473 | DeadR² 0.14442 | CloverR² 0.84036 | GDMR² 0.57206 | TotalR² 0.59732
SAVED (R²: 0.6850)


train:   3%|▎         | 1/36 [00:00<00:25,  1.37it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.15it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.03it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.54it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.81it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:05,  4.96it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.04it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.08it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.09it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.11it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.09it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.09it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.10it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.10it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.12it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.12it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:07<00:00,  5.13it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.12it/s]

tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')
tensor([0.7000, 0.7000, 0.7000, 0.7333, 0.8333], device='cuda:0')


train:   3%|▎         | 1/36 [00:00<00:27,  1.29it/s] 

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.06it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.05it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.57it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.83it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:05,  4.97it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.03it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.06it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.09it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.10it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.10it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.08it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.09it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.11it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.10it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.12it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:07<00:00,  5.12it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.12it/s]

tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')
tensor([0.6850, 0.6850, 0.6850, 0.7200, 0.8250], device='cuda:0')


Epoch 21 | TrainLoss 358.25854 | ValLoss 286.18550 | ValR² 0.6914 (BEST) | GreenR² 0.67689 | DeadR² 0.21664 | CloverR² 0.85552 | GDMR² 0.57829 | TotalR² 0.60313
SAVED (R²: 0.6914)


train:   3%|▎         | 1/36 [00:00<00:27,  1.29it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.06it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.03it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.57it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.85it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:05,  4.97it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.04it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.08it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.09it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.10it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.11it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.11it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.09it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.09it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.10it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.11it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:07<00:00,  5.12it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.12it/s]

tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')
tensor([0.6700, 0.6700, 0.6700, 0.7067, 0.8167], device='cuda:0')


train:   3%|▎         | 1/36 [00:00<00:27,  1.28it/s] 

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.05it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.03it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.57it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.84it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:05,  4.96it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.04it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.09it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.09it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.11it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.07it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.08it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.09it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.09it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.09it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.11it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:07<00:00,  5.11it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.12it/s]

tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')
tensor([0.6550, 0.6550, 0.6550, 0.6933, 0.8083], device='cuda:0')


train:   3%|▎         | 1/36 [00:00<00:27,  1.28it/s] 

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.05it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  14%|█▍        | 5/36 [00:01<00:07,  4.02it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  19%|█▉        | 7/36 [00:01<00:06,  4.55it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  25%|██▌       | 9/36 [00:02<00:05,  4.83it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  31%|███       | 11/36 [00:02<00:05,  4.97it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  36%|███▌      | 13/36 [00:03<00:04,  5.04it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  42%|████▏     | 15/36 [00:03<00:04,  5.06it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  47%|████▋     | 17/36 [00:03<00:03,  5.08it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  53%|█████▎    | 19/36 [00:04<00:03,  5.09it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  58%|█████▊    | 21/36 [00:04<00:02,  5.09it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  64%|██████▍   | 23/36 [00:05<00:02,  5.09it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  69%|██████▉   | 25/36 [00:05<00:02,  5.09it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  75%|███████▌  | 27/36 [00:05<00:01,  5.10it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  81%|████████  | 29/36 [00:06<00:01,  5.09it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  86%|████████▌ | 31/36 [00:06<00:00,  5.11it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  92%|█████████▏| 33/36 [00:07<00:00,  5.11it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:  97%|█████████▋| 35/36 [00:07<00:00,  5.10it/s]

tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')
tensor([0.6400, 0.6400, 0.6400, 0.6800, 0.8000], device='cuda:0')


train:   3%|▎         | 1/36 [00:00<00:26,  1.34it/s] 

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:   6%|▌         | 2/36 [00:00<00:14,  2.35it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:   8%|▊         | 3/36 [00:01<00:10,  3.08it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  11%|█         | 4/36 [00:01<00:08,  3.62it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  17%|█▋        | 6/36 [00:01<00:06,  4.34it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  22%|██▏       | 8/36 [00:02<00:05,  4.71it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  28%|██▊       | 10/36 [00:02<00:05,  4.90it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  33%|███▎      | 12/36 [00:02<00:04,  5.01it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  39%|███▉      | 14/36 [00:03<00:04,  5.05it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  44%|████▍     | 16/36 [00:03<00:03,  5.08it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  50%|█████     | 18/36 [00:04<00:03,  5.08it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  56%|█████▌    | 20/36 [00:04<00:03,  5.07it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  61%|██████    | 22/36 [00:04<00:02,  5.06it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  67%|██████▋   | 24/36 [00:05<00:02,  5.07it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  72%|███████▏  | 26/36 [00:05<00:01,  5.04it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  78%|███████▊  | 28/36 [00:06<00:01,  5.06it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  83%|████████▎ | 30/36 [00:06<00:01,  5.07it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  89%|████████▉ | 32/36 [00:06<00:00,  5.09it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


train:  94%|█████████▍| 34/36 [00:07<00:00,  5.09it/s]

tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')
tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


tensor([0.6250, 0.6250, 0.6250, 0.6667, 0.7917], device='cuda:0')


KeyboardInterrupt: 

In [ ]:
import gc
torch.cuda.empty_cache()
gc.collect()
del model, train_loader, val_loader, optimizer, main_scheduler

## Cross Validation Training

In [ ]:
import pandas as pd
import gc
from datetime import datetime
from sklearn.model_selection import StratifiedGroupKFold
from configs.cfg import CFG
from torch.amp import GradScaler
from dataset.biomass_dataset import *
from utils.augs import *
from configs.deterministic import *
from models.models import *
from train.train import *
from dataset.preprocess_data import *
from utils.utils import *

if __name__ == "__main__":
    set_seed(CFG.SEED, CFG.DETERMINISTIC)
    df_wide = get_df()
    # best_seed = find_best_seed(df_wide, 1000)
    sgkf = StratifiedGroupKFold(n_splits=CFG.N_FOLDS, shuffle=True, random_state=CFG.SEED)
    splitter = sgkf.split(X=df_wide, y=df_wide['biomass_bin'], groups=df_wide['group'])
    # folds_list = list(splitter)

    # check_splits(splitter, df_wide)
    # Store the best R2 score from each fold
    all_fold_best_scores = []
    group_name = f"Date_{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    for fold, (tr_idx, val_idx) in enumerate(splitter):
        print('\n' + '='*70)
        print(f'   FOLD {fold+1}/{CFG.N_FOLDS}   |   {len(tr_idx)} train / {len(val_idx)} val')
        print('='*70)
        fold_dir_512 = os.path.join('cached_folds_date_state_20_512', f"fold_{fold+1}")
        fold_dir_768 = os.path.join('cached_folds_date_state_20', f"fold_{fold+1}")
        fold_dir_1008 = os.path.join('cached_folds_date_state_20_1008', f"fold_{fold+1}")

        tr_df  = df_wide.iloc[tr_idx].reset_index(drop=True)
        val_df = df_wide.iloc[val_idx].reset_index(drop=True)

        best_r2 = train_base(fold_dir_768,tr_df,val_df,fold,group_name = group_name)
        # best_r2 = train_tree(fold_dir_768, fold, verbose=True)
        # best_r2 = train_knn(fold_dir_768, fold, verbose=True)
        
        all_fold_best_scores.append(best_r2)

    # Cleanup
    torch.cuda.empty_cache()
    gc.collect()
    # all_fold_sizes = [83,81,66,71,56]# Change by hand if folds change date
    all_fold_sizes = [76,74,90,57,60]# Change by hand if folds change state+date
    weighted_cv_score = np.average(all_fold_best_scores, weights=all_fold_sizes)

    # 2. Standard Deviation
    # For std, a simple np.std is usually fine to just show "stability," 
    # but you can stick to the simple calculation for this.
    std_cv_score = np.std(all_fold_best_scores)
    print('\n' + '='*70)
    print('         FINAL CROSS-VALIDATION SCORE')
    print('='*70)
    print(f'Public LB Score: 0.58')
    # Notice we use the weighted score here
    print(f'Local CV Score: {weighted_cv_score:.4f} ± {std_cv_score:.4f}')
    print('\nIndividual Fold Scores:')
    for i, (score, size) in enumerate(zip(all_fold_best_scores, all_fold_sizes)):
        print(f'  Fold {i+1} (n={size}): {score:.4f}')
    # Local CV Score: 0.8078 ± 0.0415
    # 0.7953 ± 0.0358 - mse
    # 512,mse: 0.7993 ± 0.0364
    # 768,mse: 0.7933 ± 0.0370
    # 1008,mse: 0.7899 ± 0.0413


/home/teo/kaggle/csiro/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Loading data...
357 training images

   FOLD 1/5   |   281 train / 76 val


NameError: name 'best_r2' is not defined